server:
  port: 8081

spring:
  application:
    name: cab-book-user
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: user-group
      auto-offset-reset: earliest